-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot exposing (..)

import Contracts.UniSwapGraph.InputObject
import Contracts.UniSwapGraph.Interface
import Contracts.UniSwapGraph.Object
import Contracts.UniSwapGraph.Scalar
import Contracts.UniSwapGraph.ScalarCodecs
import Contracts.UniSwapGraph.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.Id Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


liquidityPosition :
    SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPosition
    -> SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityPosition object_ =
    Object.selectionForCompositeField "liquidityPosition" [] object_ identity


timestamp : SelectionSet Int Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
timestamp =
    Object.selectionForField "Int" "timestamp" [] Decode.int


block : SelectionSet Int Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
block =
    Object.selectionForField "Int" "block" [] Decode.int


user :
    SelectionSet decodesTo Contracts.UniSwapGraph.Object.User
    -> SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


pair :
    SelectionSet decodesTo Contracts.UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


token0PriceUSD : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
token0PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token0PriceUSD" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


token1PriceUSD : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
token1PriceUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "token1PriceUSD" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve0 : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
reserve0 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve0" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserve1 : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
reserve1 =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserve1" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


reserveUSD : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
reserveUSD =
    Object.selectionForField "ScalarCodecs.BigDecimal" "reserveUSD" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenTotalSupply : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenTotalSupply =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenTotalSupply" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)


liquidityTokenBalance : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPositionSnapshot
liquidityTokenBalance =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenBalance" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
