-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contracts.UniSwapGraph.Object.LiquidityPosition exposing (..)

import Contracts.UniSwapGraph.InputObject
import Contracts.UniSwapGraph.Interface
import Contracts.UniSwapGraph.Object
import Contracts.UniSwapGraph.Scalar
import Contracts.UniSwapGraph.ScalarCodecs
import Contracts.UniSwapGraph.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.Id Contracts.UniSwapGraph.Object.LiquidityPosition
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecId |> .decoder)


user :
    SelectionSet decodesTo Contracts.UniSwapGraph.Object.User
    -> SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPosition
user object_ =
    Object.selectionForCompositeField "user" [] object_ identity


pair :
    SelectionSet decodesTo Contracts.UniSwapGraph.Object.Pair
    -> SelectionSet decodesTo Contracts.UniSwapGraph.Object.LiquidityPosition
pair object_ =
    Object.selectionForCompositeField "pair" [] object_ identity


liquidityTokenBalance : SelectionSet Contracts.UniSwapGraph.ScalarCodecs.BigDecimal Contracts.UniSwapGraph.Object.LiquidityPosition
liquidityTokenBalance =
    Object.selectionForField "ScalarCodecs.BigDecimal" "liquidityTokenBalance" [] (Contracts.UniSwapGraph.ScalarCodecs.codecs |> Contracts.UniSwapGraph.Scalar.unwrapCodecs |> .codecBigDecimal |> .decoder)
