-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contracts.UniSwapGraph.Object exposing (..)


type Bundle
    = Bundle


type Burn
    = Burn


type LiquidityPosition
    = LiquidityPosition


type LiquidityPositionSnapshot
    = LiquidityPositionSnapshot


type Mint
    = Mint


type Pair
    = Pair


type PairDayData
    = PairDayData


type PairHourData
    = PairHourData


type Swap
    = Swap


type Token
    = Token


type TokenDayData
    = TokenDayData


type Transaction
    = Transaction


type UniswapDayData
    = UniswapDayData


type UniswapFactory
    = UniswapFactory


type User
    = User
