-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contracts.UniSwapGraph.ScalarCodecs exposing (..)

import Contracts.UniSwapGraph.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias BigDecimal =
    Contracts.UniSwapGraph.Scalar.BigDecimal


type alias BigInt =
    Contracts.UniSwapGraph.Scalar.BigInt


type alias Bytes =
    Contracts.UniSwapGraph.Scalar.Bytes


type alias Id =
    Contracts.UniSwapGraph.Scalar.Id


codecs : Contracts.UniSwapGraph.Scalar.Codecs BigDecimal BigInt Bytes Id
codecs =
    Contracts.UniSwapGraph.Scalar.defineCodecs
        { codecBigDecimal = defaultCodecs.codecBigDecimal
        , codecBigInt = defaultCodecs.codecBigInt
        , codecBytes = defaultCodecs.codecBytes
        , codecId = defaultCodecs.codecId
        }
